<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMOGRAMAN**

**“Type Data dan Variabel”**

**Disusun Oleh :**

**Ibnu Brilliant**

**2611532024**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Rifky Yuliandra**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum Type Data dan Variabel yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemograman. Praktikum ini berfokus pada pembahasan mengenai macam macam type data dan variabel  serta penerapannya pada program python.

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secaralangsung konsep type data dan variabel pada real project.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang

Pemrograman merupakan salah satu dasar penting dalam bidang informatika. Dalam pemrograman, komputer diberikan instruksi untuk mengolah data dan menghasilkan keluaran sesuai dengan kebutuhan. Oleh karena itu, pemahaman mengenai cara menyimpan dan mengolah data menjadi salah satu hal yang penting untuk dipelajari sejak awal.

Python merupakan salah satu bahasa pemrograman yang banyak digunakan karena memiliki sintaks yang sederhana dan mudah dipahami. Dalam Python, terdapat konsep dasar yang perlu dipahami sebelum mempelajari program yang lebih kompleks, salah satunya adalah variabel dan tipe data.

Variabel digunakan untuk menyimpan suatu nilai atau data yang dapat digunakan kembali dalam program. Sementara itu, tipe data digunakan untuk menentukan jenis data yang disimpan oleh suatu variabel. Python memiliki beberapa tipe data dasar, seperti integer, float, string, dan boolean.

Pemahaman mengenai variabel dan tipe data sangat penting karena hampir setiap program membutuhkan proses penyimpanan, pengolahan, dan penggunaan data. Dengan memahami konsep tersebut, mahasiswa dapat melanjutkan pembelajaran Python ke materi yang lebih kompleks, seperti operasi aritmatika, percabangan, perulangan, fungsi, dan struktur data.

Oleh karena itu, praktikum mengenai tipe data dan variabel dilakukan sebagai dasar untuk memahami bagaimana Python menyimpan dan mengelola berbagai jenis data dalam sebuah program.

## 1.2 Tujuan

Praktikum ini bertujuan untuk:

1. Memahami pengertian variabel dalam Python.
2. Memahami pengertian tipe data dalam Python.
3. Mengenal beberapa tipe data dasar pada Python.
4. Mengetahui cara membuat dan menggunakan variabel.
5. Mengetahui cara menampilkan nilai variabel menggunakan fungsi `print()`.
6. Mengetahui cara mengetahui tipe data suatu variabel menggunakan fungsi `type()`.
8. Mengetahui cara memasukkan suatu data oleh pengguna menggunakan fungsi `input()`
7. Menerapkan variabel dan tipe data dalam program Python sederhana.

## 1.3 Manfaat

Praktikum ini memberikan pemahaman dasar mengenai penggunaan variabel dan tipe data dalam bahasa pemrograman Python. Dengan memahami kedua konsep tersebut, mahasiswa dapat mengetahui bagaimana data disimpan dan digunakan dalam sebuah program.

Selain itu, praktikum ini menjadi dasar untuk mempelajari materi Python berikutnya. Pemahaman terhadap variabel dan tipe data akan membantu mahasiswa dalam membuat program yang mampu melakukan pengolahan data secara lebih terstruktur.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

### 2.1.1 Variabel

Variabel merupakan tempat atau nama yang digunakan untuk menyimpan suatu nilai dalam program. Variabel memungkinkan data disimpan dan digunakan kembali ketika program dijalankan.

Dalam Python, variabel dapat dibuat dengan memberikan sebuah nilai menggunakan operator `=`.

Contoh:

```python
nama = "Ibnu"
umur = 20
```
Pada contoh tersebut, nama merupakan variabel yang menyimpan data berupa teks, sedangkan umur merupakan variabel yang menyimpan data berupa bilangan bulat.

Python tidak mengharuskan pengguna menentukan tipe data variabel ketika membuatnya. Tipe data akan ditentukan berdasarkan nilai yang diberikan kepada variabel tersebut.

### 2.1.2 Tipe Data

Tipe data merupakan jenis data yang digunakan untuk menentukan bentuk nilai yang disimpan dalam sebuah variabel. Python memiliki berbagai tipe data yang dapat digunakan sesuai dengan kebutuhan program.

Beberapa tipe data dasar yang digunakan dalam Python adalah:




###2.1.3 Integer

Integer atau int merupakan tipe data yang digunakan untuk menyimpan bilangan bulat, baik positif maupun negatif.

Contoh:
```python
umur = 20
jumlah = 100
suhu = -5
```

###2.1.4 Float

Float merupakan tipe data yang digunakan untuk menyimpan bilangan yang memiliki nilai desimal.

Contoh:
```python
tinggi = 163.5
berat = 55.5
nilai = 87.5
```

###2.1.5 String

String atau str merupakan tipe data yang digunakan untuk menyimpan teks. String ditulis menggunakan tanda kutip tunggal maupun tanda kutip ganda.

Contoh:
```python
nama = "Ibnu"
program_studi = "Informatika"
```

###2.1.6 Boolean

Boolean atau bool merupakan tipe data yang hanya memiliki dua nilai, yaitu True dan False. Tipe data ini biasanya digunakan untuk menyatakan kondisi benar atau salah.

Contoh:
```python
mahasiswa = True
lulus = False
```

###2.1.7 Fungsi type()

Fungsi type() digunakan untuk mengetahui tipe data yang dimiliki oleh suatu nilai atau variabel.

Contoh:
```python
umur = 20
print(type(umur))
```
Hasilnya:
```pyhton
<class 'int'>
```

###2.1.8 Fungsi input()

Fungsi input() digunakan untuk membuat program dapat menerima data secara langsung dari pengguna, sehingga nilai yang digunakan dalam program tidak harus ditentukan terlebih dahulu di dalam kode.

Contoh:
```pyhton
nama = input("Masukkan nama Anda: ")
print("Halo,", nama)
```
Hasilnya:
```pyhton
Masukkan nama Anda: Ibnu
Halo, Ibnu
```

---
## 2.2 Kode Program

### 2.2.1 Program "numerik_2611532024.py"

In [ ]:
#Buat file dengan nama Numerik_261152024.py
#nama variabel ditambah 4 digit terakhir NIM contoh: a_5500
#create a variable with numeric type value.
a_2024=100
print("The type of variable having value", a_2024, "is", type(a_2024))

#create a variable with float value.
b_2024=10.2345
print("The type of variable having value", b_2024, "is", type(b_2024))

#create a variable with complex value.
c_2024=100+3j
print("The type of variable having value", c_2024, "is", type(c_2024))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**

Penjelasan Nomor 1 Tipe Data Numerik
1. Membuat variabel bertipe integer.
Variabel a_2024 dibuat dengan nilai 100. Karena nilainya merupakan bilangan bulat, Python mengenalinya sebagai tipe data int.
2. Menampilkan tipe data integer.
Fungsi print() dan type() digunakan untuk menampilkan nilai a_2024 sekaligus mengetahui tipe datanya.
3. Membuat variabel bertipe float.
Variabel b_2024 dibuat dengan nilai 10.2345. Karena memiliki nilai desimal, variabel tersebut termasuk tipe data float.
4. Menampilkan tipe data float.
Fungsi type() digunakan untuk mengetahui tipe data dari variabel b_2024, kemudian hasilnya ditampilkan menggunakan print().
5. Membuat variabel bertipe complex.
Variabel c_2024 dibuat dengan nilai 100+3j. Nilai tersebut merupakan bilangan kompleks yang terdiri dari bagian real dan bagian imajiner, sehingga termasuk tipe data complex.
6. Menampilkan tipe data complex.
Fungsi type() digunakan untuk mengetahui tipe data variabel c_2024, kemudian hasilnya ditampilkan menggunakan print().

### 2.2.2 Program "String_2611532024.py"

In [ ]:
#Buat file dengan nama String _NIM.py
#nama variable ditambah 4 digit nim terakhir contoh: nama_1234
#ganti programnya dan ddata masing2
nama_2024="Ibnu Brilliant"
jenis_kelamin_2024='L'
alamat_2024="""
 kampus Unand
 Kec. Pauh
 Kota Padang
"""
agama_2024='islam'
print("Nama saya adalah:", nama_2024)
print("Jenis Kelamin saya adalah:",jenis_kelamin_2024)
print("Alamat saya adalah:",alamat_2024)
print("Agama saya adalah:",agama_2024)

Nama saya adalah: Ibnu Brilliant
Jenis Kelamin saya adalah: L
Alamat saya adalah: 
 kampus Unand 
 Kec. Pauh 
 Kota Padang

Agama saya adalah: islam


**Penjelasan :**

Penjelasan Nomor 2 Tipe Data String
1. Membuat variabel nama.
Variabel nama_2024 dibuat untuk menyimpan nama dalam bentuk teks. Karena data berupa teks, variabel tersebut memiliki tipe data str.
2. Membuat variabel jenis kelamin.
Variabel jenis_kelamin_2024 digunakan untuk menyimpan data jenis kelamin. Nilai 'L' ditulis menggunakan tanda kutip sehingga Python mengenalinya sebagai tipe data str.
3. Membuat variabel alamat.
Variabel alamat_2024 digunakan untuk menyimpan alamat yang terdiri dari beberapa baris. Tiga tanda kutip digunakan agar teks dapat ditulis dalam bentuk multiline string.
4. Membuat variabel agama.
Variabel agama_2024 digunakan untuk menyimpan data agama dalam bentuk teks. Karena nilainya ditulis menggunakan tanda kutip, data tersebut termasuk tipe str.
5. Menampilkan data nama.
Fungsi print() digunakan untuk menampilkan teks keterangan dan nilai yang tersimpan pada variabel nama_2024.
6. Menampilkan data jenis kelamin.
Nilai dari variabel jenis_kelamin_2024 ditampilkan menggunakan fungsi print().
7. Menampilkan data alamat.
Isi variabel alamat_2024 ditampilkan menggunakan print(). Karena alamat disimpan sebagai multiline string, hasilnya juga ditampilkan dalam beberapa baris.
8. Menampilkan data agama.
Fungsi print() digunakan untuk menampilkan nilai yang tersimpan pada variabel agama_2024.

### 2.2.3 Program "Konstanta_2611532024.py"

In [ ]:
#Buat file dengan nama Konstanta_2611532024.py
#Program ini menggunakan konstanta untuk menghitung luas lingkaran
#nama variabel ditambah 4 digit nim terakhir contoh: jari_12347



from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2024 = float(input('Masukkan nilai jari-jari: '))
luas_2024 = PI * jari_2024 * jari_2024
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_2024, luas_2024))

pi: 3.140000
Masukkan nilai jari-jari: 7
Luas lingkaran dengan jari-jari 7.00 adalah 153.86


**Penjelasan :**

Penjelasan Nomor 3 Tipe Data konstanta
1. Mengimpor Final.
Program mengimpor Final dari modul typing. Final digunakan untuk memberikan penanda bahwa suatu variabel dimaksudkan sebagai konstanta, yaitu nilai yang seharusnya tidak diubah selama program berjalan.
2. Membuat konstanta PI.
Dibuat konstanta PI dengan nilai 3.14. Nilai tersebut digunakan sebagai nilai pendekatan dari π untuk menghitung luas lingkaran.
3. Menampilkan nilai konstanta.
Fungsi print() digunakan untuk menampilkan nilai PI dengan format bilangan desimal menggunakan %f.
4. Memasukkan nilai jari-jari.
Fungsi input() digunakan untuk meminta pengguna memasukkan nilai jari-jari lingkaran. Nilai yang dimasukkan kemudian dikonversi menjadi tipe data float agar dapat digunakan dalam operasi perhitungan.
5. Menghitung luas lingkaran.
Nilai PI dan jari_2024 digunakan untuk menghitung luas lingkaran. Hasil perhitungan disimpan ke dalam variabel luas_2024.
6. Menampilkan hasil perhitungan.
Fungsi print() digunakan untuk menampilkan nilai jari-jari dan luas lingkaran. Format %.2f digunakan agar hasil ditampilkan dengan dua angka di belakang koma.

### 2.2.4 Program "Input_2611532024.py"

In [ ]:
#Buat file dengan nama Input_2611532024
#Buat program untuk menghitung luas persegi panjang
#Nama variabel ditambah 4 digit nim terakhir contoh: panjang_1234
#Program ini menggunakan fungsi input() untuk meminta pengguna
#memasukkan nilai panjang dan lebar persegi panjang
#Nilai yang dimasukkan akan dikonversi menjadi tipe data intenger
panjang_2024 = input('Masukkan nilai panjang: ')
lebar_2024 = input('Masukkan nilai lebar: ')
luas_2024 = int(panjang_2024) * int(lebar_2024)
print("Luas =", luas_2024)

**Penjelasan :**

Penjelasan Nomor 4  Fungsi Input

1. Membuat variabel panjang.
Fungsi input() digunakan untuk meminta pengguna memasukkan nilai panjang persegi panjang. Nilai yang diterima dari input() pada awalnya berupa string.
2. Membuat variabel lebar.
Fungsi input() kembali digunakan untuk meminta pengguna memasukkan nilai lebar persegi panjang. Nilai tersebut juga masih berupa string.
3. Mengonversi nilai menjadi integer.
Nilai pada variabel panjang_2024 dan lebar_2024 dikonversi menggunakan fungsi int(). Konversi ini diperlukan agar kedua nilai dapat digunakan dalam operasi aritmatika sebagai bilangan bulat.
4. Menghitung luas persegi panjang.
Nilai panjang dikalikan dengan nilai lebar untuk mendapatkan luas persegi panjang. Hasil perhitungan kemudian disimpan dalam variabel luas_2024.
5. Menampilkan hasil.
Fungsi print() digunakan untuk menampilkan hasil perhitungan luas persegi panjang kepada pengguna.

### 2.2.5 Program "Boolean_2611532024.py"

In [ ]:
#Buat file dengan nama Boolean_2611532024
#Nama variabel ditambah 4 digit nim terakhir contoh: nilai_1234
#Deklarasi variabel dengan tipe data Boolean
is_lulus_2024=True
is_cumlaude_2024=True

#Menggunakan Boolean
nilai_2024=85
batas_lulus_2024=75

#Menentukan nilai Boolean dari kondisi
status_kelulusan_2024=nilai_2024>=batas_lulus_2024 #Hasilnya akan True

print("=== Cek Kelulusan ===")
print("Nilai:", nilai_2024)
print("Apakah Lulus?:",status_kelulusan_2024)
if is_lulus_2024 and is_cumlaude_2024:
    print("Selamat, Anda lulus dnegan predikat Cumlaude")

=== Cek Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dnegan predikat Cumlaude


Penjelasan Nomor 3 — Boolean
1. Membuat variabel Boolean.
Dibuat dua variabel, yaitu is_lulus_2024 dan is_cumlaude_2024, yang masing-masing memiliki nilai True. Kedua variabel tersebut menggunakan tipe data Boolean (bool), yang hanya memiliki nilai True atau False.
2. Menentukan nilai dan batas kelulusan.
Variabel nilai_2024 diberikan nilai 85, sedangkan batas_lulus_2024 diberikan nilai 75. Kedua variabel tersebut digunakan untuk menentukan apakah nilai memenuhi batas kelulusan.
3. Menentukan status kelulusan.
Dilakukan perbandingan antara nilai_2024 dengan batas_lulus_2024 menggunakan operator >=. Karena nilai 85 lebih besar atau sama dengan 75, hasil perbandingan tersebut adalah True dan disimpan dalam variabel status_kelulusan_2024.
4. Menampilkan informasi kelulusan.
Fungsi print() digunakan untuk menampilkan judul, nilai mahasiswa, dan status kelulusan berdasarkan hasil perbandingan yang telah dilakukan.
5. Memeriksa dua kondisi Boolean.
Program menggunakan percabangan if dengan operator and. Operator and digunakan untuk memastikan bahwa is_lulus_2024 dan is_cumlaude_2024 sama-sama bernilai True.
6. Menampilkan pesan kelulusan.
Karena kedua kondisi bernilai True, kondisi pada if terpenuhi sehingga program menampilkan pesan bahwa pengguna lulus dengan predikat Cumlaude.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa variabel dan tipe data merupakan konsep dasar yang sangat penting dalam pemrograman Python. Variabel digunakan untuk menyimpan nilai yang dapat digunakan kembali dalam suatu program, sedangkan tipe data menunjukkan jenis nilai yang disimpan oleh variabel tersebut.

Pada praktikum ini dipelajari beberapa tipe data dasar Python, yaitu `int` untuk bilangan bulat, `float` untuk bilangan desimal, `str` untuk teks, dan `bool` untuk nilai benar atau salah. Selain itu, fungsi `type()` dapat digunakan untuk mengetahui tipe data yang dimiliki oleh suatu variabel Ditambah fungsi `input()` yang dapat digunakan untuk memasukkan suatu data oleh pengguna.

Praktikum juga menunjukkan bahwa variabel dapat digunakan dalam operasi aritmatika dan penggabungan teks. Dengan memahami konsep variabel dan tipe data, mahasiswa memiliki dasar yang diperlukan untuk mempelajari materi pemrograman Python yang lebih lanjut.

---
# DAFTAR PUSTAKA

Python Software Foundation. (2026). *Python 3 Documentation*. Python Software Foundation.

Lutz, M. (2013). *Learning Python* (5th ed.). O'Reilly Media.

Matthes, E. (2019). *Python Crash Course: A Hands-On, Project-Based Introduction to Programming* (2nd ed.). No Starch Press.

Microsoft. (2026). *Visual Studio Code Documentation*. Microsoft.